# Generated by Django 5.1.3 on 2024-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_wraps_wrap_top_artists_wrap_top_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
