# Generated by Django 5.1.2 on 2024-11-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_slidedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
