# Generated by Django 5.1.2 on 2024-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_wrap_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='top_genres',
            field=models.JSONField(default=list),
        ),
    ]
